name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repo
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Adjust the Node.js version if needed

      # Install pnpm
      - name: Setup pnpm
        run: npm install -g pnpm

      # Install dependencies using pnpm
      - name: Install dependencies
        run: pnpm install

      # Build the project
      - name: Build project
        run: pnpm run build

      # Copy 404.html to dist
      - name: Copy 404.html
        run: cp 404.html ./dist/404.html

      # Upload production-ready build files
      - name: Upload production-ready build files
        uses: actions/upload-artifact@v3
        with:
          name: production-files
          path: ./dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      # Download build artifact
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: production-files
          path: ./dist

      # Create CNAME file for custom domain
      - name: Create CNAME file
        run: echo 'colir.net' > ./dist/CNAME  # Replace with your custom domain

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
